// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/google/uuid"
)

type Transaction struct {
	ID      uuid.UUID
	Amount  int32
	Ownerid uuid.UUID
}

type User struct {
	ID           uuid.UUID
	Username     string
	Email        string
	Passwordhash string
}
